### ISSUE TITLE
person code types (CBSS/national registry)

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#20]
OpenAPI YAML extract below has draft data types for CBSS registry and national registry related code types (the ones with names ending on "Id")

Goal is to align these with FedVoc, and add them to belgif-person-openapi data types where useful.

FedVoc entries with related OpenAPI/Swagger entries and documentation:
HouseholdRelationType - HouseholdRelationTypeId - [doc](https://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT141_Gezinslid_20171030.pdf)
CivilState (draft) - CivilStateId - [doc](https://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT120_Burgerlijke_Staat_20210106.pdf)
Register (draft) - SubregisterId - [doc](https://www.ksz-bcss.fgov.be/nl/diensten-en-support/diensten/rijksregisterksz-registers#h2_0)

Is there an interest to include other code types as well?

```YAML
    BirthActTypeId:
      type: integer
      minimum: 0
      maximum: 99
      description: The code of the birth act type, as assigned by the National Register
    CivilStateId:
      type: integer
      minimum: 1
      maximum: 99
      description: The civil state code, as assigned by the National Register
    CohousingTypeId:
      type: integer
      minimum: 0
      maximum: 99
      description: The code of the type of cohousing, as assigned by the National Register
    ContactAddressTypeId:
      type: integer
      minimum: 1
      maximum: 99
      description: The code of the type of contact address, as assigned by the Crossroads Bank of Social Security
    HouseholdRelationId:
      type: integer
      minimum: 1
      maximum: 99
      description: The code of the household relation, as assigned by the National Register
    LegalCohabitationTerminationTypeId:
      type: integer
      minimum: 1
      maximum: 99
      description: The code of the legal cohabitation termination type, as assigned by the National Register
    NobilityTitleId:
      type: integer
      minimum: 1
      maximum: 99
      description: The code of the nobility title, as assigned by the National Register
    SubregisterId:
      type: integer
      minimum: 1
      maximum: 99
      description: The code for the (sub)register as part of the National Register
```
