### ISSUE TITLE
Standardize VAT number

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#29]
VAT number is a commonly used type, which is currently in Draft status.
Can we graduate it, and create a datatype (~ OpenAPI type)?

The current description in FedVoc is based on: https://en.wikipedia.org/wiki/VAT_identification_number 

> A value added tax identification number or VAT identification number (VATIN) is an identifier used in many countries, including the countries of the European Union, for value added tax purposes.
> 
> In the EU, a VAT identification number can be verified online at the EU's official VIES website. It confirms that the number is currently allocated and can provide the name or other identifying details of the entity to whom the identifier has been allocated. However, many national governments will not give out VAT identification numbers due to data protection laws.
> 
> The full identifier starts with an ISO 3166-1 alpha-2 (2 letters) country code (except for Greece, which uses the ISO 639-1 language code EL for the Greek language, instead of its ISO 3166-1 alpha-2 country code GR) and then has between 2 and 13 characters. The identifiers are composed of numeric digits in most countries, but in some countries they may contain letters.
> 
> Foreign companies that trade with non-enterprises in the EU may have a VATIN starting with "EU" instead of a country code, e.g. Godaddy USA EU826010755 and Amazon USA AWS EU826009064.

For the VatNumber OpenAPI type, we can check that the first two characters are letters, but restricting the length could be risky. Non-EU VAT numbers can be longer, and EU vat number length might evolve.

**Comment by pvdbosch** [comment]
from the wikipedia page, some non-EU VAT numbers allow special characters:
* Mexico:  MXP&G851223B24
* Venezuela: VEJ-30595991-8

Besides the first two letters having to be uppercase (country code) I'd keep any additional structure validation outside of the API contracts, so compatibility isn't that easily broken. Some APIs may choose to provide structure validation specific to its context (e.g. limiting to EU vat numbers only) that can be changed without breaking the contract.

**Comment by pvdbosch** [comment]
Proposed type:

```YAML
VatNumber:
  description: A value added tax identification number or VAT identification number (VATIN)
  type: string
  pattern: "^[A-Z]{2}\S+$" # 2 letter uppercase country, followed by 1 or more non-whitespace characters
```

**Comment by pvdbosch** [comment]
Will be added as data type in Organization ontology.
I'll add it to next version of belgif-organization-identifier in OpenAPI

Add in description or comments that its the international number, with two first letters the ISO 3166-1 Alpha2 code.

**Comment by pvdbosch** [comment]
Updated type, added as beta in [belgif-organization-identifier](https://github.com/belgif/openapi-organization-identifier/blob/master/src/main/openapi/organization/identifier/v1beta/organization-identifier-v1beta.yaml#L11)
```YAML
    VatNumber:
      description: An international Value-Added Tax Identification Number or VAT Identification Number (VATIN)
      type: string
      pattern: "^[A-Z]{2}.+$" # Starts with ISO 3166-1 alpha-2 country code, followed by 1 or more characters in a country-specific format
```
