### ISSUE TITLE
Standardize data types / concept schemes for NACE code

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#30]
There are different variants. Each additional digit in the code is a more detailed subcategory.
* European NACE codes
  * https://ec.europa.eu/eurostat/web/nace/overview
  * [V2](https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2/data?resId=http:%2F%2Fdata.europa.eu%2Fux2%2Fnace2%2F5224) and [V2.1](https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2.1._%28NACE_2.1%29/data)
  * up to four digits, formatted xx.yy
* Belgian NACE codes which are a superset (specialization) of european ones
  * up to seven digits
  * [FPS eco](https://economie.fgov.be/en/themes/enterprises/crossroads-bank-enterprises/services-administrations/tables-codes)
  * NSSO seems to use less digits (x>=1000 x<=99999) - [See Annex 31](https://www.socialsecurity.be/lambda/portail/glossaires/bijlagen.nsf/web/Bijlagen_Home_fr)
  * versions: Nace2003 - Nace2008

**Comment by pvdbosch** [comment]
From [what I can find](https://www.vlaio.be/nl/begeleiding-advies/start/opstart-van-je-onderneming/het-belang-van-correcte-nace-codes), there are three main contexts in which NACE-codes are used in Belgium:
* VAT (FPS Fin): at organization (enterprise) level => 5 digit version (TBC)
* ONSS: at organization + establishment level  => 5 digit version
* economical activities (CBE) : at establishment level => 2-7 variable length 

Examples:
* [on enterprise](https://kbopub.economie.fgov.be/kbopub/toonondernemingps.html?ondernemingsnummer=247499953) : NSSO + vat
* [on establishment](https://kbopub.economie.fgov.be/kbopub/toonvestigingps.html?vestigingsnummer=2123471342) : NSSO + CBE

The different variants could be represented like this:

```YAML
NaceCode:
  description: NACE activity code (international). First two digits are division of activity. Each further digits indicates an additional level of detail within the category of the previous level. The meaning of the first four digits are standard across all countries. Further digits may vary from country to country.
  type: string
  pattern: '^\d{2}\d*$'

NaceBel2008Code:
  description: Belgian NACE activity code. The meaning of the first four digits are standard across all countries. The last 3 digits are defined in the Belgian NACE 2008 list.
  type: string
  pattern: '^\d{2}\d{0,5}$'

NaceBel2008Length5Code:
  description: Belgian NACE activity code of length 5, as used for NSSO and for VAT purposes. The meaning of the first four digits are standard across all countries. The last digit is defined in the Belgian NACE 2008 list.
  type: string
  pattern: '^\d{5}$'
```

We could also use allOf to indicate a specialization (NaceCode > NaceBelCode > NaceBel5Code), TBD what the impact would be.
More specialized types are less flexible to change, but more clear in which detail level is used and more useful for input validation.

**Comment by pvdbosch** [comment]
I tweaked above openapi propositions a bit: 
* specified "of 2 up to 7 digits long" in description of NaceBel2008Code
* added comments to NaceBel2008Code and NaceBel2008Length5Code to indicate their relationship. I wouldn't put this in the schema description, bc its for authors of an OpenAPI rather than its users (clients).

These types can be added to a new openapi schema belgif-openapi-organization.

**Comment by MarcBruyland** [comment]
Closed as decided in the fedvoc meeting of 2024-06-28.

**Comment by barthanssens** [comment]
FWIW there has been a NACE2008 skos thesaurus (https://vocab.belgif.be/auth/nace2008?lang=en) available for quite a few years now

**Comment by pvdbosch** [comment]
@barthanssens , would it be best then to use http://vocab.belgif.be/auth/nace2008 as the URI of the ConceptScheme? 

A link could also be added in the comments so users can find the URIs of the individual Nace2008 concepts.

So in NaceBel2008 ConceptScheme of fedvoc:
* URI:<http://vocab.belgif.be/ns/other#nacebel2008#id> => <http://vocab.belgif.be/auth/nace2008>
* Comments: See https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/nace-bel-2008 **and http://vocab.belgif.be/auth/nace2008**

**Comment by barthanssens** [comment]
The URI for the skos:ConceptScheme is indeed http://vocab.belgif.be/auth/nace2008  
 (not http://vocab.belgif.be/ns/other#nacebel2008#id)

**Comment by pvdbosch** [comment]
OK, would be best to use the existing URI then. @MarcBruyland ,  could the changes in my previous command by applied to fedvoc?

**Comment by pvdbosch** [comment]
For the 2025 codes, from what I can find, they will only be up to 5 digits long:

* https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/nacebel-2025
* https://www.moore.be/nl/nieuws/twee-belangrijke-wijzigingen-voor-bedrijven-vanaf-1-januari-2025

Existing NaceCode notation could still be used for international scheme.
A NaceBel2025Code could be introduced for variable length 2-5
A NaceBel2008Length5Code could be introduced for fixed length 5.

An another node, do we need to extend NaceBel2025Code and NaceCode to include the top-level single letter categories?
They also can be found in the categorization on KBO e.g. https://kbopub.economie.fgov.be/kbopub/naceToelichting.html?nace.code=J , but not directly associated to enterprises.

**Comment by pvdbosch** [comment]
The top level NACE code of one letter (A-Z) has been confirmed to be used by FPS Economy.

So suggested to allow these also in the schemas:
```
NaceCode:
  description: NACE activity code (international). Either a single-letter code, or numeric code. A longer code specifies an additional level of detail within the category of the previous level. The first two digits are division of activity. The meaning of the single-letter codes and first four digits of a numeric code are standard and defined by EU. Further digits may vary from country to country.
  type: string
  pattern: '^([A-Z]{1}|\d{2}\d*)$'

NaceBel2008Code:
  description: Belgian NACE activity code of either a single letter, or numerical 2 up to 7 digits long. A longer code specifies an additional level of detail within the category of the previous level. The meaning of the single-letter codes and first four digits of a numeric code are standard across all countries. The last 3 digits are defined in the Belgian NACE 2008 list.
  type: string
  pattern: '^([A-Z]{1}|\d{5})$'
  # this is a more constrained version of the international NaceCode schema
```

About the length 7 codes: 
* they are defined in the list of FPS Economy: https://economie.fgov.be/nl/themas/ondernemingen/kruispuntbank-van/diensten-voor-administraties/codetabellen
* but not in the statbel list: https://statbel.fgov.be/nl/over-statbel/methodologie/classificaties/nace-bel-2008

On the NACE BEL 2025 codes:
* follows the same notation as 2008, but the codes themselves are backwards-incompatible (changed codes for same business meaning, new codes, split codes, ...); source: https://statbel.fgov.be/en/about-statbel/methodology/classifications/nacebel-2025
* There's no variant list with 7-digit codes published by FPS Economy available at this point. Maybe they won't maintain create one?
  * From this [source](https://www.moore.be/nl/nieuws/twee-belangrijke-wijzigingen-voor-bedrijven-vanaf-1-januari-2025):  De huidige zeven-cijferige codes, die dateren uit 2008, worden vervangen door vijfcijferige codes. De oude zeven-cijferige codes verdwijnen. Vanaf 1 januari 2025 zullen de btw en de RSZ de nieuwe structuur al hanteren. De Kruispuntbank van Ondernemingen (KBO) zal de wijziging later doorvoeren.
    * this web page isn't from a government instance however

I'd recommend to manage the 2025 codes in two separate lists then (ConceptSchemes, code tables) because they're functionally incompatible. Their value should never be used without knowing the version of the code list. 
For the notation, we could reuse the same data types, but an API should always specify which version of the code list is being used. 

If we decide to reuse the same schemas, we'd have to remove the "2008" part of the NaceBel2008Code and NaceBel2008Length5Code schemes.
