### ISSUE TITLE
[HealthCare] CompetencyCode

### ISSUE THREAD

**Issue by pvdbosch** [belgif/fedvoc#34]
Add entries for a health care provider's competency as defined by NIHDI (RIZIV-INAMI):
* data type CompetencyCode (bevoegdheidscode)
* a property competency 

OpenAPI entry:

```YAML
CompetencyCode:
  description: "<TBD>"
  type: string
  pattern: '^\d{3}$'
```
